name: Sync Image to Aliyun  Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-n54eck7xq2fljg4f.cn-hangzhou.personal.cr.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/tianzhao1020/coda:v1.6 docker://crpi-n54eck7xq2fljg4f.cn-hangzhou.personal.cr.aliyuncs.com/lsr2/tianzhao1020/coda:v1.6    
         
         
